# Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up

version: "3"
services:
  app:
    image: zsh-git-aliases-app-test:0.0.3
    environment: &environment
      - STAGE=testing
    build:
      args:
        stage: test
        version: 0.0.3
